server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - TokenRelay # Habilita el reenv√≠o del token OAuth2

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/tpi-backend}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/tpi-backend/protocol/openid-connect/certs}

logging:
  level:
    root: INFO
    ar.edu.utn.frc.backend.tpi.api_gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

keycloak:
  admin:
    url: ${KEYCLOAK_ADMIN_URL:http://keycloak:8080}
    realm: ${KEYCLOAK_ADMIN_REALM:tpi-backend}
    username: ${KEYCLOAK_ADMIN_USER:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin123}
    default-user-password: ${KEYCLOAK_DEFAULT_USER_PASSWORD:Temporal123!}

tpi:
  gateway:
    solicitudes-service-url: ${TPI_GATEWAY_SOLICITUDES_SERVICE_URL:http://localhost:8081}
    flota-service-url: ${TPI_GATEWAY_FLOTA_SERVICE_URL:http://localhost:8082}
    costos-service-url: ${TPI_GATEWAY_COSTOS_SERVICE_URL:http://localhost:8083}
