server:
  port: 8080
spring:
  application:
    name: api-gateway


  cloud:
    gateway:
      default-filters:
        - TokenRelay # Habilita el reenv√≠o del token OAuth2 a los servicios downstream
      routes:
        - id: transportes-service
          uri: http://localhost:8081
          predicates:
            - Path=/transportes/**
        - id: flota-service
          uri: http://localhost:8082
          predicates:
            - Path=/flota/**
        - id: costos-service
          uri: http://localhost:8083
          predicates:
            - Path=/costos/**

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: api-gateway
            client-secret: gateway_secret
            authorization-grant-type: authorization_code
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/tpi-backend

logging:
  level:
    root: INFO
    ar.edu.utn.frc.backend.tpi.api_gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
