server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - TokenRelay # Habilita el reenvío del token OAuth2

  security:
    oauth2:
      client: # Configuración del cliente OAuth2 para el API Gateway
        registration: # Configuración de registro del cliente OAuth2
          keycloak: # Nombre del proveedor de OAuth2
            client-id: api-gateway # ID del cliente registrado en Keycloak
            client-secret: gateway_secret # Se puede configurar como una variable de entorno
            authorization-grant-type: authorization_code # Tipo de concesión de autorización
            scope: openid, profile, email # Alcances solicitados
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/tpi-backend} # URI del emisor de tokens
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/tpi-backend} # URI del emisor de tokens para la validación de JWT

logging:
  level:
    root: INFO
    ar.edu.utn.frc.backend.tpi.api_gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

tpi:
  gateway:
    solicitudes-service-url: http://localhost:8081
    flota-service-url: http://localhost:8082
    costos-service-url: http://localhost:8083
