server:
  port: 8081
spring:
  application:
    name: solicitudes-service

  datasource:
    url: jdbc:postgresql://localhost:5432/solicitudes_db
    username: solicitudes_user
    password: solicitudes_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  jackson:
    serialization:
      fail-on-empty-beans: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/tpi-backend}

gateway:
  internal:
    url: ${GATEWAY_INTERNAL_URL:http://api-gateway:8080}

keycloak:
  admin:
    url: ${KEYCLOAK_ADMIN_URL:http://keycloak:8080}
    realm: ${KEYCLOAK_ADMIN_REALM:tpi-backend}
    username: ${KEYCLOAK_ADMIN_USER:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin123}
    default-user-password: ${KEYCLOAK_DEFAULT_USER_PASSWORD:Temporal123!}

logging:
  level:
    root: INFO
    ar.edu.utn.frc.backend.tpi.solicitudes: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
